Polishing
StoneLabs/delayed-respawn pull request #1
Opened 2021-03-01 20:14 UTC by Actr0n

2021-03-01 20:16 UTC, StoneLabs requested changes
Otherwise good

2021-03-01 20:16 UTC, StoneLabs commented on src/main/resources/fabric.mod.json
> +    "Michael 'Actron' Holzmann <17412080+Actr0n@users.noreply.github.com>
Forgot a " here. Otherwise looks good.

2021-03-05 16:52 UTC, Actr0n commented
> 
> 
> Otherwise good

done

2021-03-05 16:55 UTC, StoneLabs approved these changes

2021-03-05 16:56 UTC, merged